apiVersion: v2
name: excalidraw-complete-helm

version: v0.1.0-dev4
appVersion: v0.1.0-dev2

description: A Helm chart for Kubernetes to deploy Excalidraw Complete

keywords:
  - excalidraw
  - excalidraw-complete
  - excalidraw-complete-helm
  - helm
  - kubernetes
  - chart
  - whiteboard
  - sketches
  - visualizations

type: application

dependencies:
  - name: postgres
    version: 0.11.5
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled

sources:
  - https://github.com/jmsaRuc/excalidraw-complete-helm

maintainers:
  - name: Jens Mikkel Shcroll Andersen
    email: jensmikkelandersen@gmail.com