# Default values for excalidraw-complete.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 5

image:
  repository: ghcr.io/jmsaruc/excalidraw-complete
  tag: "latest"
  imagePullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# For the vite frontend URL, make sure to include the correct protocol (http or https).
# If https is used, tls is needed to be set in gateway.
frontendUrl: "http://excalidraw.minikube.local"

# add websocket url to allowed origins, make sure to set the correct protocol (ws or wss) and host if you change the default value
corsAllowedOrigins: "ws://excalidraw.minikube.local"



# Application log level. One of: "debug", "info", "warning", "error", "fatal", "panic"
logLevel: "info"

socketDebug: ""

service:
  annotations: {}
  type: ClusterIP
  port: 8080
  # Annotations applied for services such as externalDNS or
  # service type LoadBalancer
  # type: LoadBalancer
  # httpsPort: 443
  # annotations: {}
  # loadBalancerIP: 172.16.0.1

# Envoy gatway is a prerequisite for the helm chart, make sure you have the envoy gateway installed in your cluster, and a gateway class deployed with the same name as specified in `gatewayClassName`.
# See https://gateway.envoyproxy.io/docs/tasks/quickstart/
# Other gateway implementations might be supported in the future, but currently only envoy is supported and tested.  
gateway:
  enabled: true
  gatewayClassName: envoy
  annotations: {}
    # Example of annotations for cert-manager to automatically provision TLS certificates for the gateway
    # cert-manager.io/cluster-issuer: "my-issuer"
  hostname: excalidraw.minikube.local
  listeners:
  # If you don't need TLS, you can just use the HTTP listener and set the correct host and port. Remeber to adjust the `viteFrontendUrl` accordingly if you change the host and protocol.
    - name: http
      allowedRoutes:
          namespaces:
            from: Same
      port: 80
      protocol: HTTP
   # Example of a HTTPS listener configuration for the gateway, make sure to set the correct TLS secret and hostname if you enable this.
   # - name: https
   #   allowedRoutes:
   #       namespaces:
   #         from: Same
   #   port: 443
   #   protocol: HTTPS
   #   tls: 
   #     certificateRefs:
   #       - name: example-tls-secret

  # Two routes are needed to handle the consistent hash loadbalancing for websocket and long-polling requests, and the least request routing for the rest of the endpoints.
  consistentHashRoutes:
    - matches:
      - path:
          type: PathPrefix
          value: "/socket.io/"
      - path:
          type: PathPrefix
          value: "/google.firestore.v1.Firestore/"
  leastRequestsRoutes:
    - matches:
      - path:
          type: PathPrefix
          value: "/"

# Resource requests and limits
resources: {}   
  # requests:
  #   memory: "50Mi"
  #   cpu: "50m"
  # limits:
  #   memory: "100Mi"
  #   cpu: "100m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumeMounts: []

volumes: []

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  httpGet:
    path: /
    port: excalidraw-port

liveinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  httpGet:
    path: /
    port: excalidraw-port


startupProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 60
  httpGet:
    path: /
    port: excalidraw-port

## Configuration values for the redis deployment.
redis:
  ## Set to false if bringing your own Redis instance, and add the host under `redis.host`
  enabled: true
  #password: "<redispassword>" # If not set, a random password will be generated
  revisionHistoryLimit: 5

  #host: url of own redis instance if redis.enabled is false default: release-name-redis

  image:
    repository: redis
    tag: "8.2.2-alpine"
    imagePullPolicy: IfNotPresent

  fullnameOverride: ""
  
  startupProbe:
    exec:
      command: ["redis-cli", "ping"]
    failureThreshold: 30

  service:
    port: 6379
    type: ClusterIP

  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "100Mi"
      cpu: "100m"

## Configuration values for the postgresql dependency.
## ref: https://github.com/CloudPirates-io/helm-charts/blob/main/charts/postgres/README.md
##
postgres:
  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL
  enabled: true

  ## host: default release-name-postgres 
  ##
  ## postgresqlPort port for postgres
  ## Default to 5432
  ##
  auth:
    database: excalidraw
    username: admin
    ## Alternatively, you can specify an existing secret
    # existingSecret: excalidraw-complete-secret
    # secretKeys: 
      # passwordKey: postgres-password

  service:
    port: 5432
  ## PostgreSQL fullname Override
  ##
  fullnameOverride: ""
  
  persistence:
    ## Enable PostgreSQL persistence using Persistent Volume Claims.
    ##
    enabled: true
    ## concourse data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ## Persistent Volume Access Mode.
    ##
    accessMode: ReadWriteOnce
    ## Persistent Volume Storage Size.
    ##
    size: 8Gi