

x-excalidraw: &service-excalidraw
  build:
    context: .
    cache_from:
      - ${CACHE_FROM:-type=local,src=./tmp/.buildx-cache}
    cache_to:
      - ${CACHE_TO:-type=local,dest=./tmp/.buildx-cache-app-new,mode=max}
    platforms:
        - linux/amd64
        - linux/arm64
    dockerfile: ./Dockerfile
  image: ghcr.io/jmsaruc/excalidraw-complete:${RELEASE_TAG:-latest}
  container_name: excalidraw-complete
  restart: unless-stopped
  ports:
    - "${PORT:-3002}:${PORT:-3002}"
  volumes:
    - db-data:${LOCAL_STORAGE_PATH:-/app/db-data}
  environment:
    LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH:-/app/db-data}
    STORAGE_TYPE: ${STORAGE_TYPE:-filesystem}
    VITE_FRONTEND_URL: ${VITE_FRONTEND_URL:-http://localhost:3002}
    HOST: ${HOST:-0.0.0.0}
    PORT: ${PORT:-3002}
    LOG_LEVEL: ${LOG_LEVEL:-info}
    POSTGRES_HOST: ${POSTGRES_HOST:-excalidraw-postgres}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    POSTGRES_USER: ${POSTGRES_USER:-excalidraw}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-excalidraw}
    POSTGRES_DB: ${POSTGRES_DB:-excalidraw}
  healthcheck:
    test: ["CMD", "curl", "-f", "${VITE_FRONTEND_URL:-http://localhost:3002}"]
    interval: 30s
    timeout: 3s
    retries: 3

services:
  postgres:
    profiles:
      - postgres
    image: postgres:17.5-alpine3.22
    restart: unless-stopped
    hostname: excalidraw-postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-excalidraw}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-excalidraw}
      POSTGRES_DB: ${POSTGRES_DB:-excalidraw}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-excalidraw} -d ${POSTGRES_DB:-excalidraw}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  excalidraw-complete:
    profiles:
      - ''
    <<: *service-excalidraw
  
  excalidraw-complete-postgres:
    profiles:
      - postgres
    <<: *service-excalidraw
    depends_on:
      - postgres

volumes:
  db-data: 
  pg-data:
