

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./db-data:/app/db-data
    environment:
      LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH:-/app/db-data/}
      STORAGE_TYPE: ${STORAGE_TYPE:-filesystem}
      VITE_FRONTEND_URL: ${VITE_FRONTEND_URL:-http://localhost:3002}
volumes:
  db-data: 

