

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_BACKEND_V2_GET_URL: "${FRONTEND_URL}/api/v2/"
        VITE_APP_BACKEND_V2_POST_URL: "${FRONTEND_URL}/api/v2/post/"
        VITE_APP_LIBRARY_URL: "https://libraries.excalidraw.com"
        VITE_APP_LIBRARY_BACKEND: "${FRONTEND_URL}/libraries"
        VITE_APP_AI_BACKEND: "${FRONTEND_URL}/ai/"
        VITE_APP_PLUS_LP: "${FRONTEND_URL}/plus/"
        VITE_APP_PLUS_APP: "${FRONTEND_URL}/app/"
        VITE_APP_WS_SERVER_URL: "${FRONTEND_URL}"
        VITE_APP_FIREBASE_CONFIG: '{"apiKey":"AIzaSyAd15pYlMci_xIp9ko6wkEsDzAAA0Dn0RU","authDomain":"","databaseURL":"","projectId":"excalidraw-room-persistence","storageBucket":"","messagingSenderId":"654800341332","appId":"1:654800341332:web:4a692de832b55bd57ce0c1"}'
        VITE_APP_DISABLE_TRACKING: yes

    ports:
      - "3002:3002"
    volumes:
      - ./db-data:/app/db-data
    environment:
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH:-/app/db-data/}
      - STORAGE_TYPE=${STORAGE_TYPE:-filesystem}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3002}
volumes:
  db-data: 

