FROM node:18 AS build_ui

WORKDIR /home/node/app

COPY ./excalidraw .

ARG VITE_APP_BACKEND_V2_GET_URL
ARG VITE_APP_BACKEND_V2_POST_URL
ARG VITE_APP_LIBRARY_URL
ARG VITE_APP_LIBRARY_BACKEND
ARG VITE_APP_AI_BACKEND
ARG VITE_APP_PLUS_LP
ARG VITE_APP_PLUS_APP
ARG VITE_APP_WS_SERVER_URL
ARG VITE_APP_FIREBASE_CONFIG
ARG VITE_APP_DISABLE_TRACKING

ENV VITE_APP_BACKEND_V2_GET_URL=${VITE_APP_BACKEND_V2_GET_URL}
ENV VITE_APP_BACKEND_V2_POST_URL=${VITE_APP_BACKEND_V2_POST_URL}
ENV VITE_APP_LIBRARY_URL=${VITE_APP_LIBRARY_URL}
ENV VITE_APP_LIBRARY_BACKEND=${VITE_APP_LIBRARY_BACKEND}
ENV VITE_APP_AI_BACKEND=${VITE_APP_AI_BACKEND}
ENV VITE_APP_PLUS_LP=${VITE_APP_PLUS_LP}
ENV VITE_APP_PLUS_APP=${VITE_APP_PLUS_APP}
ENV VITE_APP_WS_SERVER_URL=${VITE_APP_WS_SERVER_URL}
ENV VITE_APP_FIREBASE_CONFIG=${VITE_APP_FIREBASE_CONFIG}
ENV VITE_APP_DISABLE_TRACKING=${VITE_APP_DISABLE_TRACKING}


RUN echo "test ${VITE_APP_BACKEND_V2_GET_URL}"
RUN npm install
RUN cd excalidraw-app && npm run build:app:docker

FROM golang:1.21-alpine AS build

COPY --from=build_ui /home/node/app/excalidraw-app/build /app/frontend

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/excalidraw-complete /app/main.go

FROM alpine:latest
COPY --from=build /app/excalidraw-complete /app/excalidraw-complete

EXPOSE 3002
CMD ["/app/excalidraw-complete"]