{{- if .Values.gateway.enabled -}}
{{- if .Capabilities.APIVersions.Has "gateway.envoyproxy.io/v1alpha1" -}}
{{- $fullName := include "excalidraw-complete.fullname" . -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $fullName }}-consistent-hash
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ $fullName }}-consistent-hash
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: QueryParams
      queryParams:
        - name: gsessionid
{{- end -}}
{{- end -}}