{{- if .Values.ingressHashLoadbalancing.enabled -}}
  {{- $fullName := include "excalidraw-complete.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- $allowedOrigins := include "excalidraw-complete.allowedOrigins" . -}}
  {{- if and .Values.ingressHashLoadbalancing.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingressHashLoadbalancing.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingressHashLoadbalancing.annotations "kubernetes.io/ingress.class" .Values.ingressHashLoadbalancing.className}}
  {{- end }}
  {{- end }}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-hash-loadbalancing
  labels:
    {{- include "excalidraw-complete.labels" . | nindent 4 }}
  {{- with .Values.ingressHashLoadbalancing.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-buffering: 'off'
    nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/upstream-hash-by: "$http_x_goog_request_params$arg_gsessionid" 
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{- $allowedOrigins -}}"
    nginx.ingress.kubernetes.io/cors-allow-methods: 'GET, PUT, POST, DELETE, PATCH, OPTIONS'
    nginx.ingress.kubernetes.io/cors-allow-headers: 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Content-Length,X-CSRF-Token,Token,session,Origin,Host,Connection,Accept-Encoding,Accept-Language,X-Goog-Api-Client,X-Firebase-GMPID,X-HTTP-Session-Id,X-Firebase-Client'
    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true'
    nginx.ingress.kubernetes.io/cors-expose-headers: 'X-HTTP-Session-Id,X-Goog-Channel-Id,X-Goog-Channel-Token'
    nginx.ingress.kubernetes.io/cors-max-age: '300'
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingressHashLoadbalancing.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingressHashLoadbalancing.className }}
  {{- end }}
{{- if .Values.ingressHashLoadbalancing.tls }}
  tls:
  {{- range .Values.ingressHashLoadbalancing.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingressHashLoadbalancing.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
  {{- end }}
  {{- end }}