{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "excalidraw-complete.redis.secret" . }}
    namespace: {{ .Release.Namespace }}
    labels:
      {{- include "excalidraw-complete.redis.labels" . | nindent 6 }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "excalidraw-complete.fullname" .)) }}
  {{- $existingRedisPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingRedisPassword = index $existingSecret.data "redis-password" }}
  {{- end }}
  {{- $redisPassword := $existingRedisPassword | default (.Values.redis.password | default (randAlphaNum 32) ) }}
  redis-password: {{ $redisPassword | b64enc | quote }}
{{- end }}