apiVersion: v1
kind: Secret
metadata:
    name: {{ template "excalidraw-complete.redis.secret" . }}
    labels:
        {{- include "excalidraw-complete.labels" . | nindent 4 }}
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}