apiVersion: v1
entries:
  excalidraw-complete-helm:
  - apiVersion: v2
    appVersion: v0.1.0-dev1
    created: "2025-11-25T09:48:30.997204742Z"
    dependencies:
    - condition: postgres.enabled
      name: postgres
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.11.5
    description: A Helm chart for Kubernetes to deploy Excalidraw Complete
    digest: 8f16a6be0bdb25fa1056a31a8edf47ca3c1a82ffc22d0c0c3f8860348e98437e
    keywords:
    - excalidraw
    - excalidraw-complete
    - excalidraw-complete-helm
    - helm
    - kubernetes
    - chart
    - whiteboard
    - sketches
    - visualizations
    maintainers:
    - email: jensmikkelandersen@gmail.com
      name: Jens Mikkel Shcroll Andersen
    name: excalidraw-complete-helm
    sources:
    - https://github.com/jmsaRuc/excalidraw-complete-helm
    type: application
    urls:
    - https://github.com/jmsaRuc/excalidraw-complete-helm/releases/download/v0.1.0-dev2/excalidraw-complete-helm-0.1.0-dev2.tgz
    version: 0.1.0-dev2
generated: "2025-11-25T09:48:30.994754613Z"
