apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
  namespace: excalidraw-complete
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - POST
      - DELETE
      - PATCH
    accessControlAllowOriginList:
      - "*" 
      - "http://*"
      - "https://*"
    accessControlAllowHeaders:
      - DNT
      - Keep-Alive
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
      - Accept
      - Content-Length
      - X-CSRF-Token
      - Token
      - session
      - Origin
      - Host
      - Connection
      - Accept-Encoding
      - Accept-Language
    accessControlAllowCredentials: true
    accessControlMaxAge: 300
    sslRedirect: true
    sslForceHost: true