name: Docker Test Build

on:
  workflow_run:
    workflows: ["Build and test Go"]
    types: [completed]

env:
    HEALTH_CHECK: false
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-app
        key: ${{ runner.os }}-buildx-app-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-app
    - name: Build and Run
      run: CACHE_TO="type=local,dest=/tmp/.buildx-cache-app-new,mode=max" CACHE_FROM="type=local,src=/tmp/.buildx-cache-app" COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 RELEASE_TAG=${{ github.sha }} docker compose up --build -d
    - name: Wait for healthchecks
      run: timeout 60s sh -c 'until docker ps | grep excalidraw-complete | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'
    - name: check health
      run: |
        if ! $(docker ps | grep excalidraw-complete | grep -q healthy); then
          echo "Container is not healthy"
          exit 1
        fi
    - name: APP::Move cache
      run: |
        rm -rf /tmp/.buildx-cache-app         # Remove the old cache.
        mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app  # Move the new cache to replace the old cache.