name: Docker Release

on:
  workflow_run:
    workflows: ["Go Release"]
    types: [completed]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }} # Don't use github.ref_name
        restore-keys: |
          ${{ runner.os }}-buildx-main
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push latest
      run: RELEASE_TAG=latest docker compose build --push --cache-from="type=local,src=/tmp/.buildx-cache-app" --cache-to="type=local,dest=/tmp/.buildx-cache-app-new,mode=max"
    - name: Build tag
      run: RELEASE_TAG=${{ github.sha }} docker compose build --push --cache-from="type=local,src=/tmp/.buildx-cache-app" --cache-to="type=local,dest=/tmp/.buildx-cache-app-new,mode=max"
    - name: APP::Move cache
      run: |
        rm -rf /tmp/.buildx-cache-app         # Remove the old cache.
        mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app  # Move the new cache to replace the old cache.
