name: Docker Test Build

on:
  workflow_run:
    workflows: ["Build and test Go"]
    types: [completed]

env:
    HEALTH_CHECK: false
jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Run Build and test
      run: docker compose up --build -d && timeout 60s sh -c 'until docker ps | grep excalidraw-complete | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'
