name: Docker Release

on:
  workflow_run:
    workflows: ["Go Release"]
    types: [completed]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build
      run: RELEASE_TAG=${GITHUB_REF#refs/*/} docker compose build
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push
      run: RELEASE_TAG=${GITHUB_REF#refs/*/} docker compose push