name: Build and test Go

on: push
  

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build excalidraw dependencies
      run: docker build -t exalidraw-ui-build excalidraw -f ui-build.Dockerfile
    - name: add to /frontend
      run: docker run -v ${PWD}/:/pwd/ -i exalidraw-ui-build cp -r /frontend /pwd 
    - name: Set up Go
    
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
